KvsAll:
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
ax_search:
  num_sobol_trials: -1
  num_trials: 10
  parameter_constraints: []
  parameters: []
  sobol_seed: 0
complex:
  class_name: ComplEx
  entity_embedder:
    +++: +++
    type: lookup_embedder
  relation_embedder:
    +++: +++
    type: lookup_embedder
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_ids.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      type: triples
    train:
      filename: train.del
      type: triples
    valid:
      filename: valid.del
      type: triples
  name: toy
  num_entities: -1
  num_relations: -1
  pickle: true
entity_ranking:
  chunk_size: -1
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: false
    relation_type: false
  tie_handling: rounded_mean_rank
eval:
  batch_size: 100
  num_workers: 0
  pin_memory: false
  split: valid
  trace_level: epoch
  type: entity_ranking
grid_search:
  parameters:
    +++: +++
  run: true
import: complex
job:
  device: cuda
  type: train
lookup_embedder:
  class_name: LookupEmbedder
  dim: 100
  dropout: 0.0
  initialize: normal_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 0.1
  normalize:
    p: -1.0
    with_grad: false
  regularize: lp
  regularize_args:
    +++: +++
    p: 2
    weighted: false
  regularize_weight: 8.0e-08
  round_dim_to: []
  sparse: false
manual_search:
  configurations: []
  run: true
model: complex
negative_sampling:
  chunk_size: -1
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: triple
  num_samples:
    o: -1
    p: 0
    s: 3
  sampling_type: uniform
  shared: false
  with_replacement: true
random_seed:
  numpy: -1
  python: -1
  torch: -1
search:
  device_pool: []
  num_workers: 1
  on_error: abort
  type: ax
train:
  abort_on_nan: true
  auto_correct: false
  batch_size: 100
  checkpoint:
    every: 5
    keep: 3
  loss: kl
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    mode: max
    patience: 4
  max_epochs: 20
  num_workers: 0
  optimizer: Adagrad
  optimizer_args:
    +++: +++
    lr: 0.2
  pin_memory: false
  split: train
  trace_level: epoch
  type: KvsAll
  visualize_graph: false
user:
  +++: +++
valid:
  early_stopping:
    min_threshold:
      epochs: 0
      metric_value: 0.0
    patience: 5
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: float("nan")
  split: valid
  trace_level: epoch
verbose: true
