dataset:
  name: toy

job:
  device: cuda
  type: search

checkpoint:
  every: 5

KvsAll:
  label_smoothing: -1.0

train:
  batch_size: 512
  loss: bce
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    factor: 0.95
    patience: 0
    threshold: 0.0001
  max_epochs: 200
  num_workers: 0
  optimizer: Adam
  optimizer_args:
    +++: +++
    lr: 0.1
  pin_memory: false
  trace_level: epoch
  type: KvsAll
  auto_correct: True

user:
  +++: +++

valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 10
  every: 5
  filter_with_test: true
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: ''
  trace_level: epoch

eval:
  batch_size: 256
  data: valid
  num_workers: 0
  pin_memory: false
  trace_level: example
  type: entity_ranking

import: sd_rescal_tucker3
model: sd_rescal_tucker3

sd_rescal_tucker3:
  class_name: SparseDiagonalRescal
  blocks: -1
  block_size: -1

lookup_embedder:
  class_name: LookupEmbedder
  dim: -1
  regularize: 'l2'
  sparse: false

search:
  num_workers: 2
  type: ax
  device_pool: [cuda:0]

ax_search:
  num_trials: 40
  num_sobol_trials: 20
  fixed_parameters:
    - name: sd_rescal_tucker3.entity_embedder.dim
      value: 128
  parameters:
    - name: train.batch_size
      type: choice
      values: [128, 256, 512]
    - name: train.max_epochs
      type: fixed
      value: 300
    - name: train.optimizer_args.lr
      type: range
      log_scale: true
      bounds: [1.e-3, 1.0]
    - name: train.lr_scheduler_args.patience
      type: range
      bounds: [1,10]
    - name: train.optimizer
      type: choice
      values: [Adam, Adagrad]
    - name: sd_rescal_tucker3.entity_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: sd_rescal_tucker3.relation_embedder.dropout
      type: range
      bounds: [-0.5, 0.5]
    - name: KvsAll.label_smoothing
      type: range
      bounds: [-0.3, 0.3]
    - name: lookup_embedder.regularize_args.weight
      type: range
      log_scale: true
      bounds: [1.e-20, 1.e-5]
    - name: lookup_embedder.regularize_args.weighted
      type: choice
      is_ordered: True
      values: [True, False]
    - name: sd_rescal_tucker3.entity_embedder.dim
      type: choice
      is_ordered: True
      values: [128, 256, 512]
    - name: sd_rescal_tucker3.relation_embedder.base_embedder.dim
      type: choice
      is_ordered: True
      values: [128, 256, 512]
    - name: sd_rescal_tucker3.blocks
      type: choice
      values: [128, 64, 32, 16, 8, 4, 2, 1]
      is_ordered: True
