job:
  device: cuda
  type: train

model: transe

dataset:
  name: fb15k-237
#  name: toy

train:
  batch_size: 256
  loss: margin_ranking
  loss_arg: 4.0
  max_epochs: 200
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
  type: negative_sampling

negative_sampling:
  num_negatives_o: 1000
  num_negatives_s: 1000
  sampling_type: uniform

valid:
  early_stopping.patience: 5
  every: 5
  filter_with_test: True
  metric: mean_reciprocal_rank_filtered_with_test

eval:
  batch_size: 512

transe:
  class_name: TransE
  entity_embedder:
    dim: 512
    initialize: uniform_
    initialize_args:
      uniform_ :
        a: -1.0
    sparse: false
    type: lookup_embedder
    regularize: l2
    regularize_args:
      weight: 1.e-05
      weighted: False
  relation_embedder:
    dim: 512
    initialize: uniform_
    initialize_args:
      uniform_ :
        a: -1.0
    sparse: false
    type: lookup_embedder
    regularize: l2
    regularize_args:
      weight: 1.e-05
      weighted: False
  l_norm: 1.