job:
  device: cuda
  type: search

model: transe

dataset:
  name: fb15k

train:
  batch_size: 256
  loss: margin_ranking
  loss_arg: 4.0
  max_epochs: 80
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
  type: negative_sampling

negative_sampling:
  num_negatives_o: 3
  num_negatives_p: 0
  num_negatives_s: 3
  sampling_type: uniform

valid:
  early_stopping.patience: 5
  every: 5
  filter_with_test: True
  metric: Accuracy

eval:
  batch_size: 512
  type: triple_classification

transe:
  class_name: TransE
  entity_embedder:
    dim: 100
    initialize: uniform_
    initialize_args:
      uniform_ :
        a: -1.0
    sparse: false
    type: lookup_embedder
    regularize: l2
    regularize_args:
      weight: 1.e-05
  relation_embedder:
    dim: 100
    initialize: uniform_
    initialize_args:
      uniform_ :
        a: -1.0
    sparse: false
    type: lookup_embedder
    regularize: l2
    regularize_args:
      weight: 1.e-05
  l_norm: 1.

ax_search:
  num_trials: 30
  num_sobol_trials: 20
  parameters:
    - name: train.optimizer
      type: fixed
      value: Adagrad
    - name: train.optimizer_args.lr
      type: range
      bounds: [0.001, 1.0]
    - name: train.loss_arg
      type: range
      bounds: [0.0001, 10.0]
    - name: transe.entity_embedder.normalize.p
      type: choice
      values: [-1., 2.]
      is_numerical: False
      is_ordered: False
    - name: transe.relation_embedder.normalize.p
      type: choice
      values: [-1., 2.]
      is_numerical: False
      is_ordered: False
    - name: lookup_embedder.regularize_args.weight
      type: range
      bounds: [0.0, 0.001]

search.num_workers: 4
train.num_workers: 4
eval.num_workers: 4
