job.type: train
dataset.name: toy
model: relational_tucker3

relational_tucker3:
  entity_embedder:
    dim: 50
    dropout: 0.02
    regularize: 'l2'
    regularize_args:
      weight: 4e-12

  relation_embedder:
    dropout: 0.3
    regularize: 'l2'
    regularize_args:
      weight: 6e-16
    base_embedder:
      dim: 50
      dropout: 0.3
      regularize: 'l2'
      regularize_args:
        weight: 6e-12

train:
  max_epochs: 50
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
    # weight_decay: 0.4e-7
valid:
  filter_with_test: True
