dataset:
#  name: toy
  name: fb15k-237

job:
  device: cuda
  type: search

search:
  num_workers: 1
  type: ax

train:
  batch_size: 512
  loss: bce
  lr_scheduler: ConstantLRScheduler
  max_epochs: 500
  num_workers: 0
  optimizer: Adagrad
  optimizer_args:
    +++: +++
    lr: 0.1
  pin_memory: false
  trace_level: epoch
  type: 1toN

checkpoint:
  every: 5

1toN:
  label_smoothing: -1.0

negative_sampling:
  num_negatives_o: -1
  num_negatives_p: 0
  num_negatives_s: 16
  sampling_type: uniform

valid:
  early_stopping:
    min_threshold:
      epochs: 25
      metric_value: 0.05
    patience: 10
  every: 5
  filter_with_test: true
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: ''
  trace_level: epoch

eval:
  batch_size: 512
  data: valid
  max_k: 10
  num_workers: 0
  pin_memory: false
  trace_level: example
  type: entity_ranking

import: sfnn
model: inverse_relations_model
inverse_relations_model.base_model.type: sfnn

# Using the practice of having no default values to detect errors in the config
# code
sfnn:
  entity_embedder:
    type: lookup_embedder
    dropout: -1.
    dim: -1
    +++: +++
  relation_embedder:
    type: lookup_embedder
    dropout: -1.
    dim: -1
    +++: +++
  hidden_dim: -1
  h1_dropout: -1.
  h2_dropout: -1.

ax_search:
  num_trials: 50
  parameters:
    - name: train.optimizer_args.lr
      type: range
      bounds: [0.0, 1.0]
    - name: inverse_relations_model.base_model.entity_embedder.dropout
      type: range
      bounds: [0., .5]
    - name: inverse_relations_model.base_model.relation_embedder.dropout
      type: range
      bounds: [0., .5]
    - name: inverse_relations_model.base_model.h1_dropout
      type: range
      bounds: [0., .5]
    - name: inverse_relations_model.base_model.h2_dropout
      type: range
      bounds: [0., .5]
    - name: inverse_relations_model.base_model.hidden_dim
      values: [256, 512, 1024, 2048, 4096, 8192]
      type: choice
      is_numerical: True
    - name: inverse_relations_model.base_model.entity_embedder.dim
      values: [128, 256, 512,]
      type: choice
      is_numerical: True
    - name: inverse_relations_model.base_model.relation_embedder.dim
      values: [128, 256, 512,]
      type: choice
      is_numerical: True
    - name: 1toN.label_smoothing
      type: range
      bounds: [-0.5 , 0.5]
    - name: lookup_embedder.regularize_weight
      type: range
      bounds: [0.0, 0.0000001]

search.num_workers: 4
train.num_workers: 4
eval.num_workers: 4