job:
  device: cuda
  type: train

model: transe

dataset:
  name: toy

train:
  batch_size: 256
  loss: margin_ranking
  loss_arg: 4.0
  max_epochs: 200
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
  type: negative_sampling

negative_sampling:
  filter_negatives: false
  num_negatives_o: 3
  num_negatives_p: 0
  num_negatives_s: 3
  sampling_type: uniform

valid:
  early_stopping.patience: 5
  every: 5
  filter_with_test: True
  metric: mean_reciprocal_rank_filtered_with_test

eval:
  batch_size: 512

transe:
  class_name: TransE
  entity_embedder:
    dim: 100
    initialize: uniform_
    sparse: true
    type: lookup_embedder
    regularize: l2
    regularize_weight: 1.e-05
  relation_embedder:
    dim: 100
    initialize: uniform_
    sparse: true
    type: lookup_embedder
    regularize: l2
    regularize_weight: 1.e-05
  l_norm: 1.
