job.type: train
dataset.name: toy

model: reciprocal_relations_model
reciprocal_relations_model.base_model.type: conve # redundant since also default

train:
  optimizer.default:
    type: Adam
    args:
      lr: 0.2
      weight_decay: 0.4e-7
  batch_size: 256
  max_epochs: 200

valid:
  early_stopping:
    patience: 5
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test

lookup_embedder:
  dim: 90
  initialize: xavier_normal_

conve:
  round_dim: True
  entity_embedder.dropout: 0.2
  relation_embedder.dropout: 0.2

