job.type: train
dataset.name: toy
model: complex

train:
  type: negative_sampling
  optimizer: Adagrad
  optimizer_args:
    lr: 0.6
    weight_decay: 0.4e-7
  loss: margin_ranking
  loss_arg: 2.0  # margin
  batch_size: 512

lookup_embedder.dim: 100

negative_sampling:
  num_samples.s: 30
  num_samples.o: -1
  num_samples.p: 30
  filtering:
    s: True
    o: True
    p: True
