job.type: train
dataset.name: toy
model: complex
train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
    weight_decay: 0.4e-7
lookup_embedder.dim: 100
#lookup_embedder.initialize: normal_
lookup_embedder.initialize: xavier_normal_
lookup_embedder.xavier_normal_args:
  gain: 1.0
train.lr_scheduler: ReduceLROnPlateau
train.lr_scheduler_args: 
  mode: max
  patience: 4

