job.type: train
dataset.name: toy
model: complex

train:
  type: negative_sampling
  optimizer: Adagrad
  optimizer_args:
    lr: 0.6
    weight_decay: 0.4e-7
  loss: margin_ranking
  loss_arg: 2.0  # margin
  batch_size: 512

lookup_embedder.dim: 100

negative_sampling:
  num_negatives_s: 30
  num_negatives_o: -1
  num_negatives_p: 30
