job.type: train
#dataset.name: toy
dataset.name: fb15k-237
#dataset.name: fb15k

train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.2
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4
  batch_size: 1024

eval.type: triple_classification

valid.every: 1
valid.metric: accuracy

model: complex
lookup_embedder:
  dim: 100
  regularize_weight: 0.0
