job.type: train
dataset.name: toy
model: inverse_relations_model
inverse_relations_model.base_model.type: conve # redundant since also default
lookup_embedder.dim: 200
lookup_embedder.initialize: xavier_normal_
conve.entity_embedder.dropout: 0.2
conve.relation_embedder.dropout: 0.2
valid:
  early_stopping:
    patience: 5
  every: 5
  filter_with_test: True
  metric: mean_reciprocal_rank_filtered_with_test
train:
  optimizer: Adam
  optimizer_args:
    lr: 0.2
    weight_decay: 0.4e-7
  batch_size: 256
  max_epochs: 200
